config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :destinations
  root to: 'destinations#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/destination.rb
class Destination < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController

  def index
    @dest = TravelCall.new
    @dest_json = @dest.get_destinations
    @rev = TravelCall.new
    @rev_json = @rev.get_reviews
    @user = TravelCall.new
    @user_json = @user.get_users

    # JSON.parse(@dest.get_destinations)["results"]["destinations"].each do |place|
    #   @dest_json.push(place)
    # end
  end

  def show

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/destinations/index.html.erb
<% @dest_json.each do |showdest| %>
  <div class="panel panel-default">
    <div class="panel-heading">
    <h3 class="panel-title"><%= showdest["name"] %>, <i>city:</i> <%= showdest["city"] %>, <i>country:</i> <%= showdest["country"] %>, <i>with an average rating:</i> <%= showdest["avg_rating"] %></h3>
  </div>
    <div class="panel-body">
      <% @rev_json.each do |showrev| %>
        <% if showrev["destination_id"] == showdest["id"] %>
          <h4> &nbsp; &nbsp;REVIEW: <%= showrev["blurb"] %></h4>
          <% @user_json.each do |showuser| %>
            <% if showrev["user_id"] == showuser["id"] %>
              <h5> &nbsp; &nbsp; &nbsp; &nbsp;USER: <a href="mailto:<%= showuser["email"] %>"><%= showuser["name"] %></a></h5>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>

  </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-light bg-light">
  <span class="navbar-text">
    <h2>Travel Destinations To Click On</h2>
  </span>
  <span class="navbar-text">
    <h3><%= link_to "Home", root_path %> | <%= link_to "Search", destinations_path %> | <%= link_to "Other Search", destinations_path %> </h3>
  </span>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/nav" %>
    <%= yield %>
  </body>
</html>